//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.ProxyAuthentication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAuthentication.IAuthenticationContract")]
    public interface IAuthenticationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/ConnectTo", ReplyAction="http://tempuri.org/IAuthenticationContract/ConnectToResponse")]
        string ConnectTo(string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/ConnectTo", ReplyAction="http://tempuri.org/IAuthenticationContract/ConnectToResponse")]
        System.Threading.Tasks.Task<string> ConnectToAsync(string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/AddNewUser", ReplyAction="http://tempuri.org/IAuthenticationContract/AddNewUserResponse")]
        bool AddNewUser(string name, string password, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/AddNewUser", ReplyAction="http://tempuri.org/IAuthenticationContract/AddNewUserResponse")]
        System.Threading.Tasks.Task<bool> AddNewUserAsync(string name, string password, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/GetCode", ReplyAction="http://tempuri.org/IAuthenticationContract/GetCodeResponse")]
        bool GetCode(string userName, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationContract/GetCode", ReplyAction="http://tempuri.org/IAuthenticationContract/GetCodeResponse")]
        System.Threading.Tasks.Task<bool> GetCodeAsync(string userName, int code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationContractChannel : WPFClient.ProxyAuthentication.IAuthenticationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationContractClient : System.ServiceModel.ClientBase<WPFClient.ProxyAuthentication.IAuthenticationContract>, WPFClient.ProxyAuthentication.IAuthenticationContract {
        
        public AuthenticationContractClient() {
        }
        
        public AuthenticationContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConnectTo(string userName, string userPassword) {
            return base.Channel.ConnectTo(userName, userPassword);
        }
        
        public System.Threading.Tasks.Task<string> ConnectToAsync(string userName, string userPassword) {
            return base.Channel.ConnectToAsync(userName, userPassword);
        }
        
        public bool AddNewUser(string name, string password, string email, string phone) {
            return base.Channel.AddNewUser(name, password, email, phone);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewUserAsync(string name, string password, string email, string phone) {
            return base.Channel.AddNewUserAsync(name, password, email, phone);
        }
        
        public bool GetCode(string userName, int code) {
            return base.Channel.GetCode(userName, code);
        }
        
        public System.Threading.Tasks.Task<bool> GetCodeAsync(string userName, int code) {
            return base.Channel.GetCodeAsync(userName, code);
        }
    }
}
